---
- name: Setup 1GB partition with XFS filesystem on second physical drive
  hosts: server2
  become: yes
  tasks:
    - name: Create 1GB partition on /dev/sdb
      community.general.parted:
        device: /dev/nvme1n1
        number: 1
        state: present
        part_type: primary
        part_end: 1GB

#    - name: Format the partition with XFS filesystem
#     community.general.filesystem:
#        fstype: xfs
#        dev: /dev/nvme1n1p1
#        force: true

    - name: Create mount point directory
      ansible.builtin.file:
        path: /extdrive
        state: directory

    - name: Mount the partition at /mnt/data
      ansible.posix.mount:
        path: /extdrive
        src: /dev/nvme1n1p1
        fstype: xfs
        state: mounted

    - name: Ensure partition is mounted on boot
      ansible.posix.mount:
        path: /extdrive
        src: /dev/nvme1n1p1
        fstype: xfs
        state: mounted
        fstab: yes

    - name: Set the correct ownership on the mount point
      ansible.builtin.file:
        path: /extdrive
        owner: root
        group: IT
        mode: '0770'
        state: directory
